import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'history-and-why-mysq2',
    'stability-badges',
    {
      type: 'category',
      label: 'Documentation',
      items: [{ type: 'autogenerated', dirName: 'documentation' }],
    },
    'api-and-configurations',
    'acknowledgements',
    {
      type: 'category',
      label: 'Contributing',
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
    },
  ],
  examples: [{ type: 'autogenerated', dirName: 'examples' }],
  faq: [{ type: 'autogenerated', dirName: 'faq' }],
};

export default sidebars;
