import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'history-and-why-mysq2',
    'api-and-configurations',
    {
      type: 'category',
      label: 'Documentation',
      items: [{ type: 'autogenerated', dirName: 'documentation' }],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [{ type: 'autogenerated', dirName: 'examples' }],
    },
    'acknowledgements',
    'contributing',
  ],
  // faq: [{ type: 'autogenerated', dirName: 'faq' }],
};

export default sidebars;
