name: CI

on:
  pull_request:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  MYSQL_PORT: 3306
  MYSQL_USER: root
  MYSQL_PASSWORD: test


jobs:
  tests-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        mysql-version: ["mysql:8.0"]

        #node-version: [10.16.0, 10.x, 12.x, 14.x, 16.x]
        #mysql-version: ["mysql:5.7", "mysql:8.0", "mariadb:10.6"]
        #use-compression: [1]
        #use-tls: [0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version:  ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Set up MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with: 
          mysql-version: ${{ matrix.mysql-version }} 
          user: root
          root-password: ${{ env.MYSQL_PASSWORD }}
      - run: npm install

      - name: Wait mysql server is ready
        run: node tools/wait-up.js
      - name: Run tests
        run: npm test