name: lint

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-manager-cache: false

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: Install ESLint + ESLint configs/plugins
        run: npm install --only=dev

      - name: Lint
        run: npm run lint
