name: lint

on:
  pull_request:
  push:
    branches: [ master ]

env:
  NODE_VERSION: 16.x

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install ESLint + ESLint configs/plugins
        run: npm install --only=dev
      - name: Lint JS files
        run: npm run lint:code
      - name: Lint JS snippets in docs
        run: npm run lint:docs