on:
  push:
    branches:
      - master
  workflow_dispatch:
name: release-please
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release/config.json
          manifest-file: .github/release/manifest.json

      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          check-latest: true
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish --provenance
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
